### ISSUE TITLE
Allow usage of custom QFieldCloud servers during project creation

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/field-tm#2833]
**Is your feature request related to a problem? Please describe.**

Follow on from #2828 
Need a way to connect to QFieldCloud instances, other than the one bundled with Field-TM, e.g. qfield.cloud.

**Describe the solution you'd like**

- Similar to adding custom ODK credentials, we need the same sort of box for QFieldCloud projects (user, pass, url)
- This could be saved in the db and the odk_central_xxx fields refactored to `custom_server_xxx`.
- Until the backend is refactored, just save them in the `odk_central_xxx` fields in the project table.

**Comment by NSUWAL123** [comment]
Don't we need to give the organization the flexibility to have ODK as well as QField? And instead of refactoring the `odk_central_xxx `to `custom_server_xxx`, we should have another var `qfield_server_xxx` if we allow organizations to have ODK and QField?
Also, we need to have the QField creds input field on organization creation.

CC: @spwoodcock @ramyaragupathy @manjitapandey

**Comment by NSUWAL123** [comment]
Oh, you are absolutely right! In that case, should we have an option to fill in ODK credentials while creating and updating the organization?

<img width="1627" height="1262" alt="Image" src="https://github.com/user-attachments/assets/643d2d9e-d17a-41fd-9a22-e9d0ca466d6d" />

**Comment by spwoodcock** [comment]
> Oh, you are absolutely right! In that case, should we have an option to fill in ODK credentials while creating and updating the organization?
> 
> <img width="1627" height="1262" alt="Image" src="https://github.com/user-attachments/assets/643d2d9e-d17a-41fd-9a22-e9d0ca466d6d" />

Yeah we can leave that as it is for now 😄

To solve this issue I would probably:
- Check the field_mapping_app var to see what type of project it is.
- If its QField, change some of the strings ODK Central --> QField.
- Save the responses in the same odk fields for now.

After that, we can refactor to make it more generic & support more mapping apps. We can possibly change the db field names too

**Comment by spwoodcock** [comment]
Ah good point, I'll add a quick endpoint to verify QField login 👍

**Comment by spwoodcock** [comment]
Done https://github.com/hotosm/field-tm/commit/9fcf05cc8767600b87e3315d56fb07431133010f
Please rebase on `dev` 👍 

On the backend, we need a change to the final QField project creation endpoint to accept optional credentials too, if the user provides them, else fallback to the server default creds (the same as the credential check endpoint)

**Comment by NSUWAL123** [comment]
> Done [9fcf05c](https://github.com/hotosm/field-tm/commit/9fcf05cc8767600b87e3315d56fb07431133010f) Please rebase on `dev` 👍
> 
> On the backend, we need a change to the final QField project creation endpoint to accept optional credentials too, if the user provides them, else fallback to the server default creds (the same as the credential check endpoint)

Thanks, Sam, for the quick update on adding the endpoint. It works fine!
But the issue still persists while creating a draft project. I guess it's trying to create the project on Central using the QField creds. Am I right??

**Comment by Sujan167** [comment]
> Is anyone working on this [#2838](https://github.com/hotosm/field-tm/issues/2838)? [@Anuj-Gupta4](https://github.com/Anuj-Gupta4) [@Sujan167](https://github.com/Sujan167) 🙏

No, we are not working on this issue on backend at the moment. Please feel free to proceed 🙏

**Comment by spwoodcock** [comment]
Ah ok thanks, it will have to wait for a bit - I'm working on many other high priority items this week & will come back to it 😄
